# Generated by Django 5.2.1 on 2025-07-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
